smsforms/urls.py
from django.conf.urls.defaults import *
from . import views


urlpatterns = patterns('',
    url(r'^edit/(?P<trigger_id>\d+)$', views.edit_triggers, name='smsforms_edit-triggers'),
    url(r'^delete/(?P<trigger_id>\d+)$', views.delete_triggers, name='smsforms_delete-triggers'),
    url(r'^view/$', views.view_triggers, name='smsforms_view-triggers'),
    url(r'^create/$', views.edit_triggers, name='smsforms_create-trigger'),

    url(r'^create_form/$', views.create_form, name='smsforms_create-form'),
    url(r'^edit_form/(?P<form_id>\d+)$', views.create_form, name='smsforms_edit-form'),
    url(r'^delete_form/(?P<form_id>\d+)$', views.delete_form, name='smsforms_delete-form'),
    url(r'^list_forms/$', views.list_forms, name='smsforms_list-forms'),
    url(r'^submit_form/(?P<form_id>\d+)$', views.list_forms, name='smsforms_submit-form'),

    )

smsforms/models.py
from django.db import models
from rapidsms.contrib.messagelog.models import Message
from rapidsms.models import Connection
from touchforms.formplayer.models import XForm
from touchforms.formplayer import api as tfapi
from datetime import datetime
import json


class DecisionTrigger(models.Model):
    """
    A trigger object that allows initiating an XForm either via a q & a session
    or a single form submission.
    """

    xform = models.ForeignKey(XForm)
    trigger_keyword = \
        models.CharField(max_length=255,
                         help_text="The keyword you would like to trigger this form with")
    final_response = \
        models.CharField(max_length=160, null=True, blank=True,
                         help_text="The response to be sent when a form is "
                                   "succesfully submitted. Leave blank for "
                                   "forms intended for decisiontree purposes.")

    context_data = models.TextField(null=True, blank=True,
                                    help_text="Context data to pass to form session (as raw json)")

    def __unicode__(self):
        return '%s' % self.trigger_keyword

    @property
    def context(self):
        return json.loads(self.context_data) if self.context_data else {}


class XFormsSession(models.Model):
    DEFAULT_SELECT_TEXT_MODE = 'vals_only'

    connection = models.ForeignKey(Connection, related_name='xform_sessions')
    session_id = models.CharField(max_length=200, null=True, blank=True)
    start_time = models.DateTimeField(blank=True, null=True)
    modified_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    error_msg = models.CharField(max_length=255, null=True, blank=True, help_text="Error message last received, if any")
    has_error = models.BooleanField(default=False, help_text="Did this session have an error?")
    ended = models.BooleanField(default=False, help_text="Has this session ended?")
    trigger = models.ForeignKey(DecisionTrigger, help_text="The trigger keyword+form that triggered this session")
    cancelled = models.BooleanField(default=False, help_text="Was this session cancelled (automatically or manually)?")
    select_text_mode = models.CharField(max_length=50, blank=True, null=True)
    message_outgoing = models.ForeignKey(Message, blank=True, null=True, related_name="message_outgoing",
                                          limit_choices_to={'direction': "O"}
                                          )
    message_incoming = models.ForeignKey(Message, blank=True, null=True, related_name="message_incoming",
                                          limit_choices_to={'direction': "I"}
                                          )

    def __unicode__(self):
        return 'Session:: Phone Number:%s, Start Time: %s, End Time: %s, Ended?: %s' % (self.connection.identity, self.start_time, self.end_time, self.ended)

    def end(self):
        now = datetime.utcnow()
        self.end_time = now
        self.modified_time = now
        self.ended = True
        self.save()

    def cancel(self):
        self.end()
        self.cancelled = True
        self.save()

    def _select_text_func(self):
        return {
            'compact': tfapi.select_to_text_compact,
            'vals_only': tfapi.select_to_text_vals_only,
            'verbose': tfapi.select_to_text_readable,
            'none': tfapi.select_to_text_caption_only,
        }[self.select_text_mode or self.DEFAULT_SELECT_TEXT_MODE]

    def question_to_prompt(self, q):
        return q.event.get_text_prompt(self._select_text_func()) \
            if q.event else q.text_prompt
                

smsforms/templates/smsforms/base.html
{% extends "layout-split-2.html" %}

{% load i18n %}

{% block javascripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}js/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.8.17.custom.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/smsforms.js" type="text/javascript"></script>
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css" />
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/smsforms.css" />
{% endblock %}


{% block auth %}
<div id="auth">
{#This is strictly speaking not necessary for smsforms, but nice to have when you're integrating into other projects#}
{#that already have these links (e.g. ARemind), and can't refer to them since we want this project to be a standalone app.#}
    {% if user.is_authenticated %}
        <a href="{% url auth_password_change %}">{% trans "Change Password" %}</a> |
	    <a href="{% url rapidsms-logout %}">{% trans "Log out" %} {{ user.username }}</a>
    {% else %}
	    <a href="{% url rapidsms-login %}">{% trans "Log in" %}</a>
    {% endif %}
</div>
{% endblock %}

smsforms/templates/smsforms/create_form.html
{% extends "smsforms/base.html" %}
    {% block stylesheets %}
        {{ block.super }}
        <link href="/formdesigner/css/smoothness/jquery-ui-1.8.14.custom.css" type="text/css" rel="stylesheet" />
{#        <link href="/formdesigner/css/screen.css" rel="stylesheet" type="text/css" media="screen, projection" />#}
        <link href="/formdesigner/css/chosen.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="/formdesigner/css/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
        <link href="/formdesigner/css/formdesigner.css" rel="stylesheet" type="text/css" media="screen, projection" />
    {% endblock %}

    {% block javascripts %}
        {{ block.super }}
        <script type="text/javascript" src="/formdesigner/js/jquery-1.6.1.js"></script>
        <script type="text/javascript" src="/formdesigner/js/jquery-ui-1.8.14.custom.min.js"></script>
        <script type="text/javascript" src="/formdesigner/js/jquery.jstree.js"></script>
        <script type="text/javascript" src="/formdesigner/js/jquery.fancybox-1.3.4.pack.js"></script>
        <script type="text/javascript" src="/formdesigner/js/chosen.jquery.min.js"></script>
        <script type="text/javascript" src="/formdesigner/js/jquery-ui-timepicker-addon.js"></script>
        <script type="text/javascript" src="/formdesigner/lib/xpath/lib/biginteger.js"></script>
        <script type="text/javascript" src="/formdesigner/lib/xpath/lib/schemeNumber.js"></script>
        <script type="text/javascript" src="/formdesigner/lib/xpath/models.js"></script>
        <script type="text/javascript" src="/formdesigner/lib/xpath/xpath.js"></script>
        <script type="text/javascript" src="/formdesigner/js/XMLWriter-1.0.0.js"></script>
        <script type="text/javascript" src="/formdesigner/js/saveButton.js?version=101"></script>
        <script type="text/javascript" src="/formdesigner/js/ui.js?version=101"></script>
        <script type="text/javascript" src="/formdesigner/js/util.js?version=101"></script>
        <script type="text/javascript" src="/formdesigner/js/model.js?version=101"></script>
        <script type="text/javascript" src="/formdesigner/js/controller.js?version=101"></script>
        <script type="text/javascript" src="/formdesigner/js/widgets.js?version=101"></script>
        <script type="text/javascript">
            $(function() {
                $("#/formdesigner button").addClass("btn");
            });
        </script>
    {% endblock %}

    {% block content %}
        <div class="module">
            <h2>Formdesigner</h2>
            <br />
            <h3>{% if xform %}Edit{% else %}Create{% endif %} your XForm here.  When done, make sure to click Save!</h3>
        </div>
        <div class="hq-oldstyle">
            <div id="formdesigner"></div>
            <script type="text/javascript">
            $(document).ready(function () {
                   formdesigner.launch({
                       rootElement: "#formdesigner",
                       staticPrefix: "/formdesigner/",
                       langs: "",
                       form: '{% if xform_data %}{{ xform_data }}{% else %}{% endif %}',
                       saveUrl: "{% if xform.id %}{% url smsforms_submit-form xform.id %}{% else %}{% url smsforms_create-form %}{% endif %}",
                       CSRF_TOKEN: "{{ csrf_token }}",
                       iconUrl: "/formdesigner/css/smoothness/images/ui-icons_888888_256x240.png"
                });
            });
            </script>
        </div>
    {% endblock %}

smsforms/templates/smsforms/edit_trigger.html
{% extends "smsforms/base.html" %}

{% block javascripts %}
    {{ block.super }}
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
{#		<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}broadcast/css/broadcast.css" />#}
{% endblock %}

{% block content %}
<div class="module">
    <h2>{% if form.instance.pk %}Edit XForm SMS Trigger{% else %}Create XForm SMS Trigger{% endif %}</h2>
    <form action="#" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class='form-action'>
            <input type='button' name='cancel' value='Cancel' />
            <input type='submit' name='submit' value="Save" />
        </div>
    </form>
</div>
{% endblock %}

smsforms/templates/smsforms/view_forms.html
{% extends "smsforms/base.html" %}
{% block javascripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}js/smsforms.js" type="text/javascript"></script>
{% endblock %}


{% block content %}
    <div class="module">
        <h2>XForms List</h2>
        {% if notice %}
        <div class="{{ success|yesno:'success,error' }}">
        {{ notice }}
        </div>
        {% endif %}
        <div class="notice">
        <form enctype="multipart/form-data" method="POST" action="">
        {% csrf_token %}
        <b>Upload a new form:</b> &nbsp;&nbsp;&nbsp;<input type="file" name="file" id="id_file" />
        <input type="submit" value="Upload!" style="float:right;"/>
        </form>
        </div>
        <table>
        {% for namespace, xforms in forms_by_namespace.items %}
            {% if forloop.first %}
            <thead>
                <th>Name</th>
                <!--th>Namespace</th-->
                <th>Created</th>
                <th>Keyword Triggers</th>
                <th>Version</th>
                <th>UI Version</th>
                <th colspan="3">Form Action</th>
                <th colspan="3">Play</th>
            </thead>
            {% endif %}
            {% for xform in xforms %}
                <tr class="{% cycle "odd" "even" %}">
                    <td>{{ xform.name }}</td>
{#                    {% if forloop.first %}#}
{#                        <td class="namespace" rowspan="{{ xforms|length }}">#}
                            {# [<a href="{% url xform_download_excel %}?xmlns={{namespace}}">excel</a>] #}
{#                            {{ namespace }}#}
{#                        </td>#}
{#                    {% endif %}#}
                    <td>{{ xform.created }}</td>
                    <td>{% for trigger in xform.decisiontrigger_set.all %}[<b>{{ trigger.trigger_keyword }}</b>] {% endfor %}</td>
                    <td>{{ xform.version }}</td>
                    <td>{{ xform.uiversion }}</td>

                    <td><a href="{% url xform_download xform.id %}">download</a></td>
                    <td><a href="{% url smsforms_edit-form xform.id %}">edit</a></td>
                    <td><a href="{% url smsforms_delete-form xform.id %}">delete</a></td>

                    <td><a href="{% url xform_play xform.id %}">touch</a></td>
                    <td><a href="{% url xform_play_kb xform.id %}">type</a></td>
                    <td><a href="{% url xform_play_all xform.id %}">full</a></td>
                </tr>
            {% endfor %}
        {% empty %}
            <tr>Sorry, no forms here.</tr>
        {% endfor %}
        <tr></tr>
        </table>
        <br />
        <a href="{% url smsforms_create-form %}" id="smsforms_create_form_button" class="button add">Create New Form</a>
    </div>
{% endblock %} 

smsforms/templates/smsforms/view_triggers.html
{% extends "smsforms/base.html" %}

{% block javascripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}js/smsforms.js" type="text/javascript"></script>
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
{#		<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}broadcast/css/broadcast.css" />#}
{% endblock %}

{% block content %}
<div class="module">
    <h2>Decision Tree Triggers</h2>
    <table id='triggers-table'>
        <thead>
            <tr>
                <th>Trigger</th>
                <th>Form</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for trigger in triggers %}
            <tr>
                <td><a href="{% url smsforms_edit-triggers trigger.id %}">{{ trigger.trigger_keyword }}</a></td>
                <td>{{ trigger.xform }}</td>
                <td><a href="{% url smsforms_edit-triggers trigger.id %}">Edit</a> <a href="{% url smsforms_delete-triggers trigger.id %}">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br />
    <a href="{% url smsforms_create-trigger %}" id="smsforms_create_trigger_button" class="button add">Create New Trigger</a>

</div>

{% endblock %}